export const HOME = '/'
export const MOLOCH = '/daos/moloch'
export const HUMANITYDAO = '/daos/humanitydao'
export const DAOS = '/daos'
export const CREATE_INFO = '/create-info'
export const NEWS = '/news'